import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"
# ###########################################
# # Gnome (Gnome Terminal Default)
# # Default colors
# [colors.primary]
# background = '#1e1e1e'
# foreground = '#ffffff'
#
# # Normal colors
[colors.normal]
# black      = '#171421'
red        = '#c01c28'		#
# green      = '#26a269'
# yellow     = '#a2734c'
# blue       = '#12488b'
# magenta    = '#a347ba'
# cyan       = '#2aa1b3'
# white      = '#d0cfcc'
#
# # Bright colors
[colors.bright]
# black      = '#5e5c64'
red        = '#f66151'		#
# green      = '#33d17a'
yellow     = '#e9ad0c'		#
# blue       = '#2a7bde'
# magenta    = '#c061cb'
# cyan       = '#33c7de'
# white      = '#ffffff'
# ###########################################


# My Customizations
[colors]
draw_bold_text_with_bright_colors = true

# [cursor]
# style = "Blinking"
# shape = "IBeam"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"


[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Underline"
blinking = "Always"
